# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date/time')),
                ('sending_date', models.DateTimeField(verbose_name='Sending date/time')),
                ('status', models.CharField(choices=[('NEW', 'New claim'), ('SENT', 'Sended claim')], max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Claims',
                'verbose_name': 'Claim',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date/time')),
                ('changing_date', models.DateTimeField(auto_now=True, verbose_name='Changing date/time')),
                ('rotation_beginning_date', models.DateTimeField(verbose_name='Rotation beginning date/time')),
                ('rotation_ending_date', models.DateTimeField(verbose_name='Rotation ending date/time')),
                ('title', models.CharField(max_length=255, verbose_name="Offer's title")),
                ('offer_type', models.CharField(choices=[('CC', 'Consumer credit'), ('MG', 'Mortgage'), ('CL', 'Car loan'), ('SME', 'SME credit')], max_length=3)),
                ('min_scoring_points', models.IntegerField()),
                ('max_scoring_points', models.IntegerField()),
                ('credit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.CreditOrganization')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'verbose_name': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date/time')),
                ('changing_date', models.DateTimeField(auto_now=True, verbose_name='Changing date/time')),
                ('client_name', models.CharField(max_length=255, verbose_name="Client's full name")),
                ('birthday', models.DateField(verbose_name="Client's birthday")),
                ('phone_number', models.CharField(max_length=50, verbose_name="Client's phone")),
                ('passport', models.CharField(max_length=100, verbose_name="Client's passport")),
                ('scoring_points', models.IntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='accounts.Partner')),
            ],
            options={
                'verbose_name_plural': 'Questionnaires',
                'verbose_name': 'Questionnaire',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.Offer'),
        ),
        migrations.AddField(
            model_name='claim',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.Questionnaire'),
        ),
    ]
