# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.Offer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='credit_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.CreditOrganization'),
        ),
    ]
