# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('claims', '0002_auto_20160520_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='credit_organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.CreditOrganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner'),
            preserve_default=False,
        ),
    ]
