# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_auto_20160523_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='accounts.Partner'),
        ),
    ]
